services:
  redis:
    image: redis:latest
    container_name: redis_rate_latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  app:
    build: .
    container_name: rate_limiter_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    restart: always    

volumes:
  redis_data: